name: Build librtlsdr

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform-name: 'linux'
          - os: macos-latest
            platform-name: 'macos'
    runs-on:
      ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.8'
      - name: Install build deps
        run:
          sudo apt-get install -y libusb-1.0-0-dev
        if: ${{ matrix.platform-name == 'linux' }}
      - name: Install dependencies
        run: |
          python -m pip install pipenv
          pipenv install --dev
      - name: Build librtlsdr source
        run: pipenv run ./tools/get_releases.py --build-types source
      - name: Test custom build
        run: pipenv run py.test tests/test_custom_build.py
      - name: Build wheel
        run: pipenv run python -m build -w
        env:
          PYRTLSDRLIB_PLATFORM: ${{ matrix.platform-name }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: 'dists'
          path: 'dist/*'
