name: Build librtlsdr

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform-name: 'linux'
            arch: 'x86_64'
          - os: macos-latest
            platform-name: 'macos'
            arch: 'x86_64'
            bottle-tag: 'monterey'
          - os: macos-latest
            platform-name: 'macos'
            arch: 'arm64'
            bottle-tag: 'arm64_monterey'
          - os: windows-latest
            platform-name: win64
            arch: AMD64
    runs-on:
      ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.8'
      - name: Install build deps
        run:
          sudo apt-get install -y libusb-1.0-0-dev
        if: ${{ matrix.platform-name == 'linux' }}
      - name: Install libusb
        run: |
          brew uninstall --ignore-dependencies libusb
          brew fetch --force --bottle-tag $BOTTLE_TAG libusb
          export BOTTLE_PATH=$(brew --cache --bottle-tag=$BOTTLE_TAG libusb)
          brew install $BOTTLE_PATH
        if: ${{ matrix.platform-name == 'macos' }}
        env:
          BOTTLE_TAG: ${{ matrix.bottle-tag }}
      - name: Install pipenv
        run: python -m pip install pipenv
      - name: Update Pipfile.lock
        run: pipenv lock
        if: ${{ matrix.platform-name == 'win64' }}
      - name: Install dependencies
        run: pipenv install --dev

      # Linux and macos
      - name: Build librtlsdr source
        run: pipenv run python tools/get_releases.py --build-types source --macos-arch=$MACOS_ARCH
        if: ${{ matrix.platform-name != 'win64' }}
        env:
          MACOS_ARCH: ${{ matrix.arch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test custom build
        run: pipenv run py.test tests/test_custom_build.py
        if: ${{ matrix.platform-name != 'win64' }}
        env:
          MACOS_ARCH: ${{ matrix.arch }}

      # Windows
      - name: Get librtlsdr release
        run: pipenv run python tools/get_releases.py --build-types windows --build-types w32 --build-types w64 --build-types static
        if: ${{ matrix.platform-name == 'win64' }}

      - name: Test build
        run: pipenv run py.test tests/test_repo_build.py
        if: ${{ matrix.platform-name == 'win64' }}


      - name: Build wheel
        run: pipenv run python -m build -w
        env:
          PYRTLSDRLIB_PLATFORM: ${{ matrix.platform-name }}
          PYRTLSDRLIB_ARCH: ${{ matrix.arch }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: 'dists'
          path: 'dist/*'
